### ISSUE TITLE
Putting the username in navbar if user is authenticated

### ISSUE THREAD

**Issue by matija077** [igorpejic/bbet#9]
U Satelizer examplu on pomocu service-a u backendu-u dobije podatke o useru.

**Comment by igorpejic** [comment]
Napraviti cu ovo veceras.
Molim te imenuj brancheve npr. issue#6_username_in_view.

**Comment by igorpejic** [comment]
Na backend strani je zavrseno. Frontend cu izmjeniti tako da se ponasa u skladu s https://github.com/johnpapa/angular-styleguide#route-resolve-promises

**Comment by matija077** [comment]
Oces to danas ili sutra?

**Comment by igorpejic** [comment]
Rjesit cu sutra to. Refactorirat cu sve vezano uz auth.

Planovi za dalje: moramo se naci ovaj vikend.

**Comment by igorpejic** [comment]
https://news.ycombinator.com/item?id=2388560

**Comment by matija077** [comment]
Closed by #11
